#!/bin/bash

# URL location
# https://fedoraproject.org/wiki/How_to_create_and_use_a_Live_CD
if (( $# < 3 ))
then
	echo "Syntax: $0 <ksFiles> <cacheLoc> <CDLabel>" >&2
	exit 1
fi

pathToKickstartFileks="$1"
tmpcacheLocation="$2"
cdLabel="$3"

livecd-creator --verbose --config="$pathToKickstartFileks" --fslabel="$cdLabel" --cache="$tmpcacheLocation"
